// <auto-generated />
using System;
using MentorConnect.Users.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MentorConnect.Users.Infrastructure.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20250219023123_CascadeDelete")]
    partial class CascadeDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MentorConnect.Users.Domain.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Extra")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("MentorConnect.Users.Domain.Entities.Mentee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Extra")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Mentee");
                });

            modelBuilder.Entity("MentorConnect.Users.Domain.Entities.Mentor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Extra")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Mentor");
                });

            modelBuilder.Entity("MentorConnect.Users.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MentorConnect.Users.Domain.Entities.Admin", b =>
                {
                    b.HasOne("MentorConnect.Users.Domain.Entities.User", "BasicInfo")
                        .WithOne("AdminInfo")
                        .HasForeignKey("MentorConnect.Users.Domain.Entities.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasicInfo");
                });

            modelBuilder.Entity("MentorConnect.Users.Domain.Entities.Mentee", b =>
                {
                    b.HasOne("MentorConnect.Users.Domain.Entities.User", "BasicInfo")
                        .WithOne("MenteeInfo")
                        .HasForeignKey("MentorConnect.Users.Domain.Entities.Mentee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasicInfo");
                });

            modelBuilder.Entity("MentorConnect.Users.Domain.Entities.Mentor", b =>
                {
                    b.HasOne("MentorConnect.Users.Domain.Entities.User", "BasicInfo")
                        .WithOne("MentorInfo")
                        .HasForeignKey("MentorConnect.Users.Domain.Entities.Mentor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasicInfo");
                });

            modelBuilder.Entity("MentorConnect.Users.Domain.Entities.User", b =>
                {
                    b.Navigation("AdminInfo");

                    b.Navigation("MenteeInfo");

                    b.Navigation("MentorInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
